# lilac_registry.rb — Registry class + Lilac module-level façade.
#
# Registry owns the live state of components in the DOM (registered classes,
# mounted instances, the MutationObserver). The module-level `class << self`
# block at the bottom is what users normally touch:
# `Lilac.register` / `Lilac.start` / `Lilac.template`.

module Lilac
  # Owns the live state of components in the DOM:
  #   - registered classes by name
  #   - mounted instances by id
  #   - the MutationObserver that drives dynamic mount/unmount
  #
  # A single Registry instance lives on the Lilac module
  # (`Lilac.registry`); the module-level `register` / `start`
  # methods are thin delegators.
  class Registry
    COMPONENT_ID_ATTR = "data-component-id"

    def initialize
      @component_classes = {}
      @components = {}
      @next_component_id = 0
      @observer = nil
      @observer_callback = nil
    end

    def register(name, klass)
      @component_classes[name.to_s] = klass
    end

    def component_for_element(js_element)
      attr = js_element.call(:getAttribute, COMPONENT_ID_ATTR)
      return nil if attr.js_null?
      @components[attr.to_s.to_i]
    end

    # Mount all data-component elements under `root_js` in two passes:
    #
    #   1. Pre-order: instantiate, register, link parent, run
    #      `prepare_setup`. After this all exposed values in this
    #      subtree are populated, so any `lookup` called in pass 2
    #      finds them.
    #
    #   2. Post-order: run `setup`. Children before parents, so
    #      `refs.x.component.method` from a parent's setup sees its
    #      children fully initialised.
    #
    # Idempotent by virtue of the underlying ops: `install_observer`
    # returns early if `@observer` is already set, `mount_subtree`
    # skips elements that already carry `data-component-id`, and
    # `prune_disconnected_components` is safe to repeat. So calling
    # `Lilac.start` multiple times (user-written + builder-auto-injected,
    # or test-suite re-invocation after a DOM swap) only mounts new
    # components and never double-mounts existing ones.
    def start(root_js = nil)
      root_js ||= JS.global[:document][:body]
      # install_observer must precede mount_subtree: if a component's setup
      # inserts nested data-component nodes (e.g. bind_list with template:),
      # MO needs to be watching to mount them on the next microtask.
      install_observer
      prune_disconnected_components
      # Fetch <link rel="lilac-bundle"> resources and inject their
      # <template> + <script type="text/ruby"> contents into the page
      # before scanning definitions. See lilac-proposals.md for the
      # bundle-fetch delivery strategy.
      fetch_lilac_bundles
      # Collect component definitions from <template> elements + outer
      # data-component= elements, then expand data-use= placeholders by
      # injecting markup from the matching definition. See ADR-29 for
      # data-component / data-use semantics.
      definitions = collect_definitions
      expand_uses(definitions)
      mount_subtree(root_js)
      nil
    end

    def reset!
      @components.each_value(&:unmount)
      @components = {}
      @component_classes = {}
      @next_component_id = 0
      return unless @observer
      @observer.call(:disconnect)
      JS.release_callback(@observer_callback)
      @observer = nil
      @observer_callback = nil
    end

    def mount_subtree(root_js)
      return if root_js.js_null? || root_js.typeof != "object"
      collected = []
      collect_components(root_js, collected)

      instances = []
      collected.each do |el_js|
        instance = instantiate_component(el_js)
        next unless instance
        instances << instance
        instance.prepare_setup_phase
      end

      instances.reverse_each(&:mount)
    end

    def unmount_subtree(root_js)
      return if root_js.js_null? || root_js.typeof != "object"
      collected = []
      collect_components(root_js, collected)
      collected.each do |el_js|
        wid = el_js.call(:getAttribute, COMPONENT_ID_ATTR)
        next if wid.js_null?
        id = wid.to_s.to_i
        instance = @components.delete(id)
        next unless instance
        instance.unmount
        begin
          el_js.call(:removeAttribute, COMPONENT_ID_ATTR)
        rescue StandardError
          # element may have been GC'd by host; ignore.
        end
      end
    end

    # Public lookup variant: returns nil instead of raising on lookup
    # error. Used by directive scanner (data-prop-* auto-fill) where a
    # missing class is non-fatal — the scanner just skips auto-fill.
    def find_component_class(name)
      resolve_component_class(name)
    rescue StandardError
      nil
    end

    private

    # Fetch all <link rel="lilac-bundle"> resources, parse them as HTML,
    # and inject their <template> + <script type="text/ruby"> contents
    # into document.body. Bundles are typically generated by `lilac build
    # --delivery=bundle` but can also be hand-written (the bundle file is
    # just a concatenation of .lil contents in HTML form).
    #
    # The injection happens before collect_definitions so the templates
    # become part of the document's definition table.
    def fetch_lilac_bundles
      document = JS.global[:document]
      links = document.call(:querySelectorAll, 'link[rel="lilac-bundle"]')
      n = links[:length].to_i
      return if n == 0

      i = 0
      while i < n
        link = links[i]
        href = link[:href].to_s
        i += 1
        next if href.empty?

        begin
          response = JS.global.call(:fetch, href).await
          unless response[:ok].js_bool
            JS.global[:console].call(
              :error,
              "[lilac] Failed to fetch lilac-bundle #{href.inspect}: HTTP #{response[:status]}"
            )
            next
          end
          html = response.call(:text).await.to_s
        rescue StandardError => e
          JS.global[:console].call(
            :error,
            "[lilac] Failed to fetch lilac-bundle #{href.inspect}: #{e.message}"
          )
          next
        end

        inject_bundle_content(html)
      end
    end

    # Parse the bundle HTML and append its <template> + <script type="text/ruby">
    # children to document.body. Newly created <script> elements are
    # auto-evaluated by the browser; static <script> from DOMParser is
    # not, so we must clone its textContent into a fresh element.
    def inject_bundle_content(html)
      parser = JS.global[:DOMParser].new
      doc = parser.call(:parseFromString, html, "text/html")
      body = JS.global[:document][:body]

      # <template> elements: append as-is so collect_definitions picks them up.
      templates = doc.call(:querySelectorAll, "template")
      tn = templates[:length].to_i
      ti = 0
      while ti < tn
        body.call(:appendChild, templates[ti].call(:cloneNode, true))
        ti += 1
      end

      # <script type="text/ruby">: evaluate via mruby's `eval` (available
      # in the :full target via mruby-eval, excluded from :compiled).
      # Browser does not auto-evaluate <script type="text/ruby"> after
      # appendChild because the MIME type is non-standard. :compiled
      # bundles should not contain these (script bundling goes through
      # the .mrb path instead).
      scripts = doc.call(:querySelectorAll, 'script[type="text/ruby"]')
      sn = scripts[:length].to_i
      si = 0
      while si < sn
        src = scripts[si][:textContent].to_s
        si += 1
        next if src.strip.empty?

        begin
          eval(src)
        rescue NameError, NoMethodError
          # `eval` unavailable (likely :compiled target without
          # mruby-eval). Skip silently; :compiled bundles shouldn't
          # carry <script type="text/ruby">.
          JS.global[:console].call(
            :warn,
            "[lilac] <script type=\"text/ruby\"> in lilac-bundle requires :full target (mruby-eval)"
          )
          break
        end
      end
    end

    # Resolve a `data-component` name to a class. Explicit `Lilac.register`
    # always wins; otherwise delegate name → constant lookup to
    # `Lilac::ComponentName` and validate the result is a Component subclass.
    def resolve_component_class(name)
      explicit = @component_classes[name]
      return explicit if explicit
      klass = ComponentName.find_class(name)
      return nil unless klass
      unless klass.is_a?(Class) && klass < Lilac::Component
        raise Error, "data-component=#{name.inspect} resolved to #{klass}, " \
                     "which is not a Lilac::Component subclass. " \
                     "Rename the class or call Lilac.register with a different name."
      end
      klass
    end

    def collect_components(root_js, out)
      stack = [root_js]
      until stack.empty?
        node = stack.pop
        next if node.js_null?
        next if node[:nodeType].to_i != 1
        if node.call(:hasAttribute, "data-component").js_bool ||
           node.call(:hasAttribute, "data-use").js_bool
          out << node
        end
        # Do not descend into a `data-each` element's children: those
        # children are the row template and live only as snapshot until
        # dispatch_each clones them per item. Mounting them as standalone
        # components would race against parent's bind_template_hook and
        # leave them with unresolved `data-prop-X="it.field"` attribute
        # values. The cloned rows are inserted by bind_list and picked
        # up via MutationObserver, with `it`-resolved attributes.
        next if node.call(:hasAttribute, "data-each").js_bool
        kids = node[:children]
        next if kids.js_null?
        kn = kids[:length].to_i
        ki = kn - 1
        while ki >= 0
          stack << kids[ki]
          ki -= 1
        end
      end
    end

    def instantiate_component(el_js)
      existing_attr = el_js.call(:getAttribute, COMPONENT_ID_ATTR)
      return nil if !existing_attr.js_null?
      name = el_js.call(:getAttribute, "data-component")
      # data-use= elements identify their target via the `data-use` attribute
      # after expand_uses has injected the markup. Both attributes are
      # accepted here so the same instantiate path works for both.
      if name.js_null?
        name = el_js.call(:getAttribute, "data-use")
      end
      return nil if name.js_null?
      klass = resolve_component_class(name.to_s)
      unless klass
        Lilac.logger.warn("No component registered or resolvable for name: #{name.to_s.inspect}")
        return nil
      end
      @next_component_id += 1
      id = @next_component_id
      el_js.call(:setAttribute, COMPONENT_ID_ATTR, id.to_s)
      instance = klass.new(el_js)
      @components[id] = instance
      parent = nearest_ancestor_component(el_js)
      parent.add_child(instance) if parent
      instance
    end

    # Scan <template> elements (inside any depth of nesting) and outer
     # data-component= elements to build a {name => element} table that
    # `expand_uses` consults when injecting markup into data-use= elements.
    # Duplicate names are reported via console.error; the first occurrence
    # wins so the run can continue (build-time check catches the same case
    # earlier when CLI is used).
    def collect_definitions
      definitions = {}
      duplicates = []
      document = JS.global[:document]

      # <template> 内の data-component= 要素 (定義のみ)
      templates = document.call(:querySelectorAll, "template")
      tn = templates[:length].to_i
      ti = 0
      while ti < tn
        tpl = templates[ti]
        content = tpl[:content]
        unless content.js_null?
          inner = content.call(:querySelectorAll, "[data-component]")
          in_len = inner[:length].to_i
          ii = 0
          while ii < in_len
            el = inner[ii]
            name = el.call(:getAttribute, "data-component").to_s
            if definitions.key?(name)
              duplicates << name
            else
              definitions[name] = el
            end
            ii += 1
          end
        end
        ti += 1
      end

      # <template> 外の data-component= 要素 (定義 + 利用)
      outside = document.call(:querySelectorAll, "[data-component]")
      on = outside[:length].to_i
      oi = 0
      while oi < on
        el = outside[oi]
        name = el.call(:getAttribute, "data-component").to_s
        if definitions.key?(name)
          duplicates << name
        else
          definitions[name] = el
        end
        oi += 1
      end

      duplicates.uniq.each do |name|
        JS.global[:console].call(
          :error,
          "[lilac] Duplicate component definition: #{name.inspect}. " \
            "Each component name must be defined only once per page."
        )
      end

      definitions
    end

    # For each data-use="X" element in the document, inject markup from
    # the matching definition when the element is empty. Unknown names
    # are reported via console.error. After expansion, data-use= elements
    # are picked up by collect_components and mounted via the normal path.
    def expand_uses(definitions)
      document = JS.global[:document]
      uses = document.call(:querySelectorAll, "[data-use]")
      un = uses[:length].to_i
      ui = 0
      while ui < un
        use_el = uses[ui]
        name = use_el.call(:getAttribute, "data-use").to_s
        template_el = definitions[name]
        if template_el.nil?
          JS.global[:console].call(
            :error,
            "[lilac] Unknown component referenced by data-use=#{name.inspect}. " \
              "No matching data-component=#{name.inspect} found in this page."
          )
          ui += 1
          next
        end

        # 空判定: innerHTML が whitespace のみなら template から markup 注入
        inner_html = use_el[:innerHTML].to_s
        if inner_html.strip.empty?
          use_el[:innerHTML] = template_el[:innerHTML]
        end
        ui += 1
      end
    end

    def nearest_ancestor_component(el_js)
      node = el_js[:parentElement]
      while !node.js_null? && node.typeof == "object"
        attr = node.call(:getAttribute, COMPONENT_ID_ATTR)
        if !attr.js_null?
          return @components[attr.to_s.to_i]
        end
        node = node[:parentElement]
      end
      nil
    end

    def install_observer
      return if @observer
      doc = JS.global[:document]
      target = doc[:body]
      return if target.js_null?
      callback = JS.callback do |mutations|
        n = mutations[:length].to_i
        i = 0
        while i < n
          rec = mutations[i]
          added = rec[:addedNodes]
          removed = rec[:removedNodes]
          an = added[:length].to_i
          rn = removed[:length].to_i
          ai = 0
          while ai < an
            node = added[ai]
            mount_subtree(node) if node[:nodeType].to_i == 1
            ai += 1
          end
          ri = 0
          while ri < rn
            node = removed[ri]
            unmount_subtree(node) if node[:nodeType].to_i == 1
            ri += 1
          end
          i += 1
        end
      end
      obs = Lilac.__window__[:MutationObserver].new(callback)
      obs.call(:observe, target, JS.object(childList: true, subtree: true))
      @observer = obs
      @observer_callback = callback
    end

    # Defensive sweep used at `Lilac.start` to drop registry entries
    # whose DOM root is no longer connected (e.g., leftover from a
    # previous test that didn't call `Lilac.reset!`). NOT called from
    # the MO callback: transient body mutations during another fiber's
    # await would otherwise falsely prune live components — `unmount_subtree`
    # on the MO's `removedNodes` is the authoritative cleanup path.
    def prune_disconnected_components
      stale = []
      @components.each do |id, instance|
        root_js = instance.root.to_js
        stale << id unless root_js[:isConnected].js_bool
      end
      stale.each do |id|
        instance = @components.delete(id)
        instance&.unmount
      end
    end
  end

  # ---- Module-level façade ---------------------------------------
  #
  # Thin delegators to the singleton Registry. Most user code only
  # ever touches these: `Lilac.register`, `Lilac.start`.
  class << self
    def registry
      @registry ||= Registry.new
    end

    def register(name, klass)
      registry.register(AttrName.new(name, kind: "data-component"), klass)
    end

    def start(root_js = nil)
      registry.start(root_js)
    end

    def reset!
      registry.reset!
    end

    def find_for_element(js_element)
      registry.component_for_element(js_element)
    end

    # Module-level shortcut to clone a `<template data-template="...">`
    # outside any component context. Inside a component, prefer the instance
    # method `template(name)` so that any listeners attached to refs in
    # the cloned content get auto-cleanup tracking.
    def template(name, &block)
      Template.from_document(name, &block)
    end
  end
end
